#
# This file is needed for KH to redirect /reports to a separate Superset set instance running with and AWS domain name 
# since we could not get a Superset subdomain in time
#
services:
  frontend:
    labels:
      traefik.http.routers.reports.rule: "Host(`${O3_HOSTNAME}`) && PathPrefix(`/reports`)"  
      traefik.http.routers.reports.entrypoints: "websecure"
      traefik.http.routers.reports.middlewares: reports-redirectregex
      traefik.http.middlewares.reports-redirectregex.redirectregex.regex: https://${O3_HOSTNAME}/reports
      traefik.http.middlewares.reports-redirectregex.redirectregex.replacement: https://${SUPERSET_HOSTNAME}